"""
Modelos de datos del formulario
Author: Josué Romero
Date: 12/12/2025
"""

CHECKLISTS = {
    "pc": {
        "titulo": "Checklist Proquinal PC 2025",
        "empresa": "Proquinal",
        "tipo": "PC",
        "plantilla": "plantilla_pc.xlsx",
        "icono": "💻",
        "color": "primary",
        "descripcion": "Para portátiles y desktop",
        "preguntas": [
            'CON USUARIO LOCAL SOPORTE. Con usuario administrador local crear el usuario local "Soporte", asignarle contraseña y agregarlo al grupo Administradores (desde compmgmt.msc).',
            'Habilitar el usuario Administrador y renombrarlo a "Adminpc_pqn", asignarle contraseña.',
            "Realizar windows update.",
            "Realizar actualización de drivers desde la página oficial del fabricante o usando SupportAssist.",
            "Verificar que windows 11 >= 24h2 esté activo.",
            "Activar características adicionales de framework 3.5 (desde optionalfeatures).",
            "Instalar las fuentes corporativas ubicadas en recursospqn$/instaladores sistemas/fuentes corporativas.",
            'Particionar el disco duro: para disco de 500 gb asignar 250 para d: y el resto para c:, para disco de 1tb asignar 600 para d: y el resto para c:. La partición d: debe llamarse "Datos".',
            'Subir el equipo al dominio de red proquinal.com, el nombre del equipo debe contener el serial. Ejemplo: "cby45tf-pqn-col" usando los últimos siete dígitos del serial.',
            'En la descripción del equipo colocar: "activo xxxx, correo@spradling.group".',
            'Desde el directorio activo en la ou "Computers" asignar descripción y luego mover el equipo a la ou "Equipos Proquinal".',
            "Instalar teamviewer host desde la web oficial.",
            "Registrar el dispositivo en la consola de administración teamviewer con la nomenclatura: primer nombre y apellido más el hostname del equipo.",
            "Instalar forticlient vpn-only desde la web oficial.",
            "Instalar citrix workspace app desde la web oficial.",
            "Instalar java jre 8 versión 341 desde recursospqn$/instaladores sistemas/java 8 341.",
            "Instalar .net framework 3.5 desde la página de Microsoft.",
            "Instalar adobe acrobat reader pdf desde la web oficial sin mcafee y en español.",
            "Instalar dell support assist o lenovo services bridge desde la web oficial.",
            "Instalar microsoft teams desde la web oficial.",
            "Instalar google chrome enterprise desde la web oficial.",
            "Instalar office 365 desde office.com con el perfil del destinatario.",
            'Instalar oracle copiando las carpetas "ORAWIN95" y "ORA9i" en c:\\ y luego importar el regedit correspondiente.',
            "Borrar carpetas previas de oracle: orawin95.old, ora9i.old, orapqn.old si aparecen.",
            "Crear la carpeta c:/listados.",
            "Copiar y pegar las carpetas orapqn y backup de turin en c:/windows.",
            "Crear variable path para ingreso oracle web con valor: c:/windows/orapqn/lib60 (solo si es portátil).",
            "Crear variable path para oracle (nombre: tns_admin, valor: o:/tnsnames).",
            "Probar acceso a aplicaciones colombia con las credenciales, teniendo conectada la unidad o://172.16.1.22/orapqn$.",
            "Reemplazar archivo host copiando y pegando el archivo ubicado en recursospqn$/instaladores sistemas/host (solo para portátiles).",
            "Agregar en propiedades de red dns 172.16.1.1 como principal y 172.16.1.32 como alternativo (solo para equipos de escritorio pqn-col).",
            "CON USUARIO DE DOMINIO. Cambiar la configuración de energía colocando nunca con corriente alterna, con batería 3 horas y desactivar el inicio rápido (desde powercfg.cpl).",
            'Incluir equipo a las redes wi-fi "SpradlingGroup2" y "SpradlingGroupCol".',
            "Agregar o quitar programas como xbox, solitario, tiempo, outlook (new), noticias, etc.",
            "Direccionar mis documentos a la carpeta d:/datos.",
            'Configurar outlook (classic) con archivos .ost en "d:/correo (no borrar)".',
            "Dejar sobre el perfil de correo la plantilla de firma fija o verificar que el usuario la tenga predeterminada.",
            'Iniciar teams con el correo del usuario y desactivar la opción "iniciar teams automáticamente".',
            "Habilitar uso de onedrive si el usuario tiene licencia y reposar backup en la raíz de la partición d:.",
            "Descargar todos los archivos en el equipo local siempre que la partición d: lo permita.",
            "Predeterminar adobe acrobat reader pdf.",
            "Habilitar conexión a escritorio remoto con el usuario de dominio desde sysdm.cpl.",
            "Habilitar macros y activex en excel y colocar a turin (file://172.16.1.22) como sitio de confianza desde inetcpl.cpl.",
            "Buscar automáticamente actualizaciones de office 365.",
            "Conectar unidades de red necesarias según el usuario.",
            "Crear acceso directo a backup turin.",
            "Revisar que exista la carpeta de backup en turin al ejecutar el archivo .bat.",
            "Copiar accesos directos de aplicaciones colombia y costa rica y dejar archivo .bat en el escritorio para refrescar o:/.",
            "Copiar accesos directos de word, excel, outlook y teams en el escritorio.",
            "Configurar seguridad de java para acceso de oracle web co-cr en modo privado y público.",
            "Dejar accesos directos en formato .exe del oracle web co-cr verificando funcionamiento.",
            "Cambiar la configuración regional para separación de miles (,) y decimales (.) desde intl.cpl.",
            "Instalar impresoras del área o la más cercana al puesto de trabajo.",
            "Dejar como predeterminada la página https://spradling.group/es-la en edge y chrome.",
            "Instalar módulo de acronis backup y registrar en la consola creando carpeta de backup en d:/datos/[año en curso] (solo directores y gerentes).",
            "Aplicar política de backup 2023 en la consola de acronis y confirmar funcionamiento (solo directores y gerentes).",
            "Colocar en los navegadores los marcadores del usuario (si aplica).",
            "Verificar que el software instalado cuente con licencia.",
            "Verificar e instalar programas adicionales según el usuario: pdf24, powerbi, scribe, sap, bizagi, iris, scada, etc.",
            "Validar que el perfil del usuario tenga habilitado el mfa desde intune.",
            "Verificar que el equipo quede con actualizaciones al día (windows, office, winget update).",
            "Desde la bios setup habilitar contraseña admin y system (solo si es portátil).",
            "Realizar inicio de sesión en mayté con el perfil del usuario verificando título, localizaciones, perfil predeterminado, responsable y grupos.",
            "Habilitar punto de restauración para la unidad c: y crear un punto con la fecha actual.",
            "Asignar activo fijo si corresponde.",
            "Actualizar datos en oracle web co. con los valores correspondientes para equipo y monitor.",
            "Diligenciar checklist y guardarlo en checklist$/2025/pqn.",
            "Revisar en intune categoría, organización, usuario, etiqueta y pertenencia a grupos.",
            "Sincronizar la cuenta desde configuración y reiniciar al finalizar para aplicar cambios de intune.",
            'Revisar en entra id que solo aparezca una vez y esté como "microsoft entra hybrid joined".',
            'Revisar en defender que el nombre del equipo termine en "x.proquina.com", tenga la etiqueta de compañía y que el otro tenga "equipos_baja" y esté excluido.',
            "Borrar desde intune, entra y defender el equipo antiguo para liberar licencias.",
            "Verificar que las particiones del disco duro estén auto cifradas.",
            "Realizar acta de entrega ubicada en checklist$/actas de entrega, copiarla, renombrarla, editarla e imprimirla.",
            "Solicitar a la supervisora a. parga el traslado del equipo mediante teams compartiendo número de activo de equipo y monitor.",
            "Realizar mantenimiento preventivo si el equipo supera seis meses de uso.",
            "Realizar limpieza de pantalla y teclado.",
            "Realizar el traslado del equipo viejo, dejarlo minipelado, marcado y ubicado en el puesto de la supervisora a. parga y publicar el recibimiento en teams.",
        ],
    },
    "terminales": {
        "titulo": "Checklist Proquinal Terminales 2025",
        "empresa": "Proquinal",
        "tipo": "Terminales",
        "plantilla": "plantilla_terminales.xlsx",
        "icono": "🖥️",
        "color": "success",
        "descripcion": "Para terminales de planta",
        "preguntas": [
            'CON USUARIO SOPORTE. El usuario de configuración inicial se crea como: "Soporte" y se asigna contraseña.',
            "Realizar Windows Update.",
            "Realizar actualización de drivers en el equipo.",
            'Habilitar usuario administrador y cambiar el nombre a: "Adminpc_pqn" (no olvidar deshabilitar el usuario "Soporte").',
            "Verificar activación de la licencia de Windows.",
            "Instalar .NET Framework 3.5 desde la página de Microsoft.",
            "Activar características adicionales de Framework 3.5 (desde appwiz.cpl).",
            "Agregar o quitar programas.",
            'Subir el equipo al dominio (proquinal.com). El nombre del equipo debe contener el Service Tag. Ejemplo: "CBY45TF-PQN-COL" [equipos Lenovo: usar los últimos 7 caracteres del serial].',
            'En la descripción del equipo, colocar: "Activo" (con A mayúscula), espacio, número de activo y correo. Ejemplo: "Activo 17800, user@spradling.group".',
            "Instalar Oracle (copiar carpetas ORAWIN95 y ORA9i, importar registro).",
            "Borrar carpetas anteriores de Oracle: ORANT.OLD, ORAWIN95.OLD, ORAPQN.OLD, ORACLEXE.OLD, ORA9I.OLD.",
            'Crear la carpeta "C:\\ Listados".',
            "Instalar Acrobat Reader desde internet (última versión).",
            "Instalar última versión de Java (versión 8-341, última compatible con Oracle).",
            "Desactivar actualización automática de Java.",
            'Copiar la carpeta ORAPQN en y el backup de TURIN en "C:\\ WINDOWS".',
            'Configuración de la variable PATH para ingreso a Oracle Web ("C:\\ ORAPQN\\ LIB60") e Innovación.',
            'Configuración de la variable de entorno "TNS_ADMIN" con valor: "O:\\ tnsnames".',
            "Agregar en propiedades de red: DNS 172.16.1.1 como principal y 172.16.1.32 como alternativo.",
            'Verificar por Regedit que aparezca la variable SCADA: nombre de cadena: "Path_Scada"; valor: "\\\\172.16.1.96\\scada$".',
            'Verificar por Regedit que aparezca la variable para Porterías (si aplica): nombre de cadena: "Path_Visitas"; valor: "C:\\ fotos_visitas".',
            'CON USUARIO DE DOMINIO. Cambiar la configuración de energía del equipo: colocar "Nunca" en las opciones de energía, batería con solo 3 horas, y desactivar el inicio rápido.',
            'Enrolar el equipo (agregar cuenta de correo en "Acceder al trabajo o colegio"). Validar que esté en el grupo de equipos Proquinal del AD.',
            "Habilitar conexión a Escritorio Remoto con el usuario del equipo.",
            'Colocar a TURIN ("file://172.16.1.22") como sitio de confianza desde Opciones de Internet.',
            "Predeterminar Acrobat Reader para abrir archivos PDF.",
            'Habilitar asistencia remota (instalar TeamViewer Host Customizado 15) y registrarlo en la consola de administración (validar que tenga la extensión "911").',
            'Crear archivo .BAT para reconexión con la carpeta: "O:\\172.16.1.22\\ orapqn$" en caso de desconexión.',
            "Instalar Citrix Online (última versión).",
            'Copiar accesos directos de aplicaciones Colombia y Costa Rica (crear .BAT en el ícono de Oracle para conexión a "O:\\").',
            "Instalar visores de Office.",
            "Instalar Microsoft Edge y Google Chrome.",
            "Configurar Edge para visualización de páginas en modo Internet Explorer. Agregar link(s) de Oracle Web a la lista de sitios permitidos (compatibilidad IE).",
            "Configurar seguridad de Java para acceso a Oracle Web.",
            'Cambiar configuración regional para separación de miles (",") y decimales (".").',
            "Crear acceso directo a Daruma: https://proquinal.darumasoftware.com/app.php/staff/ (dejar como favorito en el navegador).",
            "Crear acceso directo a Mayte: https://mayte.spradling.group/ (dejar como favorito en el navegador).",
            "Crear acceso directo a la página de Sustancias Químicas: https://spradling.aybapps.net/PROQUINAL.SUSTANCIAS/(S(bfumxph5htfsk0jv0dpbke5k))/InicioSustancias.aspx.",
            'Configurar acceso a SCADA desde navegador: "\\\\172.16.1.96\\".',
            "Instalar impresoras del área correspondiente (si aplica).",
            "Dejar predeterminada la página: https://spradling.group/es-la en todos los navegadores.",
            'Configurar AutoLogon del usuario desde Regedit: modificar "AutoAdminLogon" (cambiar valor de 0 a 1); "DefaultUserName" (usuario de la terminal con dominio);',
            'Crear clave: "DefaultPassword" con el valor correspondiente (contraseña del usuario).',
            "Verificar que el equipo tenga todas las actualizaciones al día (Windows, Office, etc.).",
            "Habilitar punto de restauración automática para la unidad C: y crear un punto de restauración.",
            "Subir el equipo a Windows 11.",
            "Asignar Activo Fijo.",
            'Realizar inventario en el sistema: físico (incluir número de RAF y activos que se cambian) y digital (guardar en "D:\\ Imagen (No Borrar)).',
            "Diligenciar los datos en Oracle del activo correspondiente. Equipo: 1, 2, 4, 5, 6, 7, 8, 79, 300, 331 (nombre de quien realiza el inventario); 339, 385, 413, 414, 415, 449, 451, 464 (código del empleado, solo números). Monitor: 1, 2, 4, 13, 15, 77, 79, 331, 413, 415, 453, 464.",
            'Diligenciar check list en "D:\\ Imagen (No Borrar).',
            "Revisar que el equipo se visualice en el servidor de Intune y Defender.",
            "Confirmar borrado del equipo antiguo en Intune y Defender (para liberar licencias).",
            "Realizar acta de entrega del equipo.",
            "Realizar traslado del equipo antiguo al área de soporte.",
            "Mantenimiento preventivo de CPU.",
            "Limpieza de pantalla.",
            "Realizar traslado del equipo viejo y dejarlo marcado con: usuario, fecha y responsable.",
        ],
    },
    "macos": {
        "titulo": "Checklist Proquinal MacOS 2025",
        "empresa": "Proquinal",
        "tipo": "MacOS",
        "plantilla": "plantilla_macos.xlsx",
        "icono": "🍎",
        "color": "dark",
        "descripcion": "Para MacBook e iMac",
        "preguntas": [
            'CON USUARIO ADMINPC_PQN. El usuario de configuración inicial se crea como: "Adminpc_pqn" y se asigna contraseña.',
            "Realizar actualizaciones de MacOS.",
            "Instalar TeamViewer Host (última versión) en la máquina y registrarlo en la consola de administración.",
            "Crear usuario correspondiente al propietario de la máquina.",
            "CON USUARIO DE DOMINIO. Ingresar con el usuario de la máquina.",
            "Realizar la instalación del portal de Microsoft para enrolamiento por Intune.",
            "Validar correcto registro en la consola de Intune y Defender.",
            "Instalar licencia de Office correspondiente a la licencia asignada al usuario de la máquina.",
            "Configurar la suite de Office con la cuenta del usuario.",
            "Configurar OneDrive en la máquina (validar si el usuario desea que los archivos se descarguen o se mantengan en la nube).",
            "Instalar Microsoft Teams. Dar permisos para compartir pantalla y audio.",
            "Instalar Adobe Cloud (si el usuario tiene licencia).",
            "Validar con el usuario qué aplicativos de la suite de Adobe necesita e instalar los requeridos.",
            "Instalar Google Chrome y FortiClient VPN.",
            "Predeterminar Acrobat Reader para abrir archivos PDF.",
            "Validar con el área de Infraestructura los permisos de navegación para el equipo.",
            "Realizar el paso de datos del equipo anterior a la nueva máquina.",
            "Revisar que el equipo tenga instalada la última versión de macOS (Monterey, Ventura o Sonoma; priorizar la más reciente).",
            "Configurar hardware externo que utilice el usuario (tableta de dibujo, graphic pen, etc.).",
            'Configurar FileVault: 1) Abrir Preferencias del Sistema. 2) Seleccionar "Seguridad y privacidad". 3) Seleccionar "FileVault". 4) Seleccionar "Activar FileVault".',
        ],
    },
    "tablets": {
        "titulo": "Checklist Proquinal Tablets 2025",
        "empresa": "Proquinal",
        "tipo": "Tablets",
        "plantilla": "plantilla_tablets.xlsx",
        "icono": "📱",
        "color": "info",
        "descripcion": "Para celulares y tablets",
        "preguntas": [
            "Antes de iniciar sesión, enrolar en Intune escaneando el código QR.",
            "La tablet aparece en Intune al escanear el código QR.",
            'Loguear la cuenta de Play Store corporativa: "soportesistemaspqncol@gmail.com".',
            "Iniciar sesión en Office 365 con la cuenta corporativa del usuario.",
            "Habilitar el inicio de sesión por PIN (4 dígitos) y tomar nota para entregar al usuario.",
            "Habilitar el bloqueo de la tablet para 15 minutos (no menos).",
            "Instalar Outlook.",
            "Instalar Office (Word, Excel, PowerPoint).",
            "Instalar Power BI.",
            "Instalar OneDrive.",
            "Instalar TeamViewer Host.",
            "Instalar Adobe Reader.",
            'Instalar la app "HubSpot" desde Play Store.',
            "Crear acceso directo a Daruma: https://proquinal.darumasoftware.com/app.php/staff/ (dejar como favorito en el navegador).",
            "Crear acceso directo a Mayte: https://mayte.spradling.group/ (dejar como favorito en el navegador).",
            "Crear acceso directo a la Biblioteca de Productis: https://library.spradling.group/auth/login (dejar como favorito en el navegador).",
            "Dejar como predeterminada la página https://spradling.group/en-la en todos los navegadores.",
            "Verificar si el usuario utiliza otro tipo de software como IRIS, archivo de planeación, software de diseño, etc.",
            "Verificar que el software instalado en el equipo cuente con licencia.",
            "Dejar la tablet con las últimas actualizaciones disponibles.",
            "Asignar activo fijo.",
            'Realizar inventario en el sistema: 1) Físico (incluir número de RAF y activos que se cambian). 2) Digital en "D:\\ Imagen (No Borrar).',
            "23. Diligenciar los datos en Oracle del activo correspondiente: Equipo: 1 - 2 - 4 - 5 - 6 - 7 - 8 - 79 - 300 - 331 - 339 - 385 - 413 - 414 - 415 - 449 - 451 - 464. Monitor: 1 - 2 - 4 - 13 - 15 - 77 - 79 - 331 - 413 - 415 - 453 - 464.",
            'Diligenciar checklist en "D:/Imagen (No Borrar).',
            "Revisar que se pueda ver en el servidor de Defender e Intune.",
            "Realizar el traslado del equipo viejo y dejarlo marcado con usuario, fecha y responsable.",
        ],
    },
    "calypso": {
        "titulo": "Checklist Calypso CCS CBQ 2025",
        "empresa": "Calypso",
        "tipo": "CCS-CBQ",
        "plantilla": "plantilla_calypso.xlsx",
        "icono": "⚙️",
        "color": "warning",
        "descripcion": "Para equipos Calypso",
        "preguntas": [
            "DEBE USAR AUTOPILOT. Iniciar sesión con el equipo hasta el momento que pide internet",
            "Enrolar dentro del tenant de Intune",
            "Validar que el equipo se pueda ver desde Entra",
            "Asignar el usuario en la inscripción de equipos por Autopilot",
            "Agregar el equipo al grupo de Intune: GRP_Dispositivos Windows Autopilot CCS-COL (para la instalación de aplicaciones)",
            "Confirmar que el equipo aparezca enrolado en Entra y ajustar las etiquetas: tipo de dispositivo, etiqueta de empresa, grupos asignados (Equipos CCS-COL + el de despliegue de apps)",
            "Iniciar sesión con el usuario asignado en el equipo (la sesión se inicia con el correo electrónico)",
            'Habilitar usuario administrador "Adminpc_ccs"',
            "Verificar activación de licencia de Windows",
            "Instalar .NET Framework 3.5",
            "Realizar Windows Update",
            "Verificar controladores del equipo (actualización de drivers)",
            "Agregar o quitar programas (eliminar todo lo relacionado con apps de juegos y redes sociales); dejar solo apps corporativas",
            "Particionar el disco duro (si es posible): disco 500 GB (250 GB para D: y el resto para C:), disco 1 TB (600 GB para D: y el resto para C:)",
            "Instalar Comerssia (si lo requiere) ***solo PDV*** (tener presente que la hora regional cambia)",
            "En el grupo de trabajo del equipo, colocar la ciudad o sede a la que pertenece",
            'En la descripción del equipo, colocar "Activo [número de activo], correo@spradling.group" (Ej.: Activo 175608, hola.pqn@spradling.group)',
            "Cambiar el nombre del equipo (debe contener el Service Tag). Ej.: P08DTGF-[CCS-CBQ]-COL. *Equipos Lenovo: usar los últimos 7 caracteres del serial*. Colocar grupo de trabajo con usuario",
            "CON USUARIO DE AZUREAD: Cambiar la configuración de energía del equipo (colocar 'nunca' en las opciones de energía. En batería: solo 3 horas)",
            "Direccionar 'Mis documentos' a la carpeta D:\\ Datos",
            "Instalar Office según licencia del usuario (validar ejecución de tarea desde Intune)",
            "Instalar Acrobat Reader (validar ejecución de tarea desde Intune)",
            "Instalar Chrome Enterprise (validar ejecución de tarea desde Intune)",
            "Configurar el correo con el archivo OST en D:\\ Datos\\ Correo",
            "Instalar Teams (habilitar el inicio en segundo plano, no al inicio con Windows)",
            "Habilitar uso de OneDrive del usuario (si tiene licencia); guardar ubicación en D:",
            "Deshabilitar opción 'Ahorrar espacio y descargar los archivos cuando los use'; no sincronizar Documentos, Escritorio ni Imágenes",
            "Predeterminar Acrobat Reader para abrir archivos PDF",
            "Validar que el equipo tome el fondo de pantalla según la política de Intune",
            "Habilitar asistencia remota (validar tarea desde Intune: TeamViewer Host 15) y registrarlo en la consola de administración",
            "Instalar fuentes corporativas",
            "Copiar accesos directos a las aplicaciones de Office",
            "Cambiar la configuración regional para separación de miles y decimales ('.' para decimales, ',' para miles)",
            "Crear acceso directo en el escritorio a SAP (mstsc -v sapcalypso.spradling.group:9546)",
            "Instalar software VPN Fortinet (solo instalar, no configurar)",
            "Dejar como página predeterminada https://www.tiendascalypso.com en todos los navegadores",
            "Crear acceso directo a MAYTE: https://mayte.spradling.group/es-la (dejar como favorito en navegador)",
            "Habilitar conexión a escritorio remoto con el usuario del equipo",
            "Validar activación de MFA en el correo del usuario",
            "Habilitar contraseña de ingreso al sistema operativo (si es portátil)",
            "Verificar si el usuario utiliza otro tipo de software como Adobe, AutoCAD, software de diseño, etc.",
            "Verificar que el equipo quede con actualizaciones al día (Windows, Office, etc.)",
            "Asignar activo fijo (AF)",
            "Habilitar punto de restauración automática para la unidad C:",
            "Realizar inventario en el sistema (físico y digital en D:\\ Imagen (No Borrar)",
            "Diligenciar check list en D:\\ Imagen (No Borrar)",
            "Crear imagen de la partición C:\\ [SISTEMAPQN] y readme informativo en D:\\ Imagen (No Borrar) ¡¡¡solo equipos especiales!!!",
            "Revisar que se pueda ver en el servidor de antivirus Defender",
            "Revisar que el equipo se vea desde Intune y Entra sin estar duplicado; retirar los equipos antiguos de estas plataformas",
        ],
    },
}


def get_checklist(tipo: str) -> dict:
    """Obtener checklist por tipo"""
    return CHECKLISTS.get(tipo)


def get_all_checklists() -> dict:
    """Obtener todos los checklists"""
    return CHECKLISTS


def checklist_exists(tipo: str) -> bool:
    """Verificar si existe un checklist"""
    return tipo in CHECKLISTS
