CHECKLISTS = {
    "pc": {
        "titulo": "Checklist Proquinal PC 2025",
        "empresa": "Proquinal",
        "tipo": "PC",
        "plantilla": "plantilla_pc.xlsx",
        "icono": "💻",
        "color": "primary",
        "descripcion": "Para portátiles y desktop",
        "preguntas": [
            'CON USUARIO LOCAL SOPORTE. Crear usuario local "Soporte", asignar contraseña y agregarlo al grupo administradores (Desde compmgmt.msc).',
            'Habilitar usuario administrador y renombrarlo a "Adminpc_pqn", asignar contraseña.',
            "Realizar windows update.",
            "Realizar actualización de drivers (Desde la página oficial del fabricante o usando supportassist).",
            "Instalar y activar características adicionales de framework 3.5 (Desde página microsoft).",
            "Instalar fuentes corporativas ubicadas en (recursospqn$/Instaladores Sistemas/Fuentes corporativas).",
            'Particionar el disco duro. Para disco de 500gb (250 para d y el resto para c). Para disco de 1tb (600 para d y el resto para c). La partición d debe llamarse "Datos". Disco de 250gb no se particiona.',
            'Subir el equipo al dominio de red (proquinal.com). El nombre del equipo debe contener el serial del equipo. Ejemplo "Cby45tf-pqn-col" (Tomar siempre los últimos siete dígitos del serial más la compañía y su regional).',
            'En la descripción del equipo colocar. Ejemplo "Activo xxxxx, correo@spradling.group".',
            'Desde el directorio activo en la ou "Computers" asignar la descripción. Ejemplo "Activo xxxxx, correo@spradling.group". Luego mover el equipo a la ou "Equipos proquinal".',
            "Instalar teamviewer host desde (recursospqn$/Instaladores Sistemas/Teamviewer/2025 - Host) y registrar en la consola admin (Primer nombre y apellido más el hostname del equipo entre paréntesis). Luego comprobar actualizaciones del programa.",
            'Instalar mediante el manual oracle erp proquinal s.a.s ubicado en "Recursospqn$/Recursos 2014/Oracle Install/Manual de instalación oracle.pdf".',
            'Renombrar carpetas de oracle "OraWin95.old" y "Ora9i.old".',
            'Copiar y pegar las carpetas de oracle en c:/ desde la ruta "//recursospqn$/Recursos 2014/Oracle/Oracle Client/Orawin95 y Ora9i/Usuario estandar" las carpetas "Ora9i" y "OraWin95".',
            "Crear la carpeta c:/Listados.",
            'Exportar regedit del usuario o ejecutar según área desde "//recursospqn$/Recursos 2014/Oracle/Oracle Client/Oracle64".',
            "Instalar java jre 8 versión 341 (Desde recursospqn$/Instaladores Sistemas/Java 8 341).",
            "Copiar y pegar las carpetas orapqnen en la raíz de c:/ y backup de turin en (c:/Windows).",
            "Crear variable path para ingreso oracle web con valor c:/Orapqn/lib60 (Solo si es portátil).",
            "Crear variable de entorno para oracle (Nombre tns_admin, valor o:/tnsnames).",
            "Probar acceso a aplicaciones colombia con tus credenciales (Antes debe conectar la unidad de red o://172.16.1.22/orapqn$).",
            "Instalar forticlient vpn-only (Desde la web oficial).",
            "Instalar citrix workspace app (Desde la web oficial).",
            "Instalar adobe acrobat reader pdf (Desde la web oficial sin mcafee y en español).",
            "Instalar dell support assist o lenovo services bridge (Desde la web oficial).",
            "Instalar google chrome enterprise (Desde la web oficial).",
            'Reemplazar archivo host, copiar y pegar el archivo desde "Recursospqn$/Instaladores Sistemas/Host" (Desde drivers, solo si es portátil).',
            "Agregar en propiedades de red dns. Como principal 172.16.1.1 y como alternativo 172.16.1.32 (Solo para equipos de escritorio pqn-col).",
            "CON USUARIO DE DOMINIO. Cambiar la configuración de energía del equipo. Colocar nunca con corriente alterna, con batería 3 horas y desactivar inicio rápido (Desde powercfg.cpl).",
            "Direccionar mis documentos a la carpeta d:/Datos (Datos no es la unidad d).",
            'Conectar las redes wifi "Spradlinggroup2" y "Spradlinggroupcol".',
            "Agregar o quitar programas como xbox, solitario, tiempo, noticias, phone.",
            "Instalar office 365 si el usuario tiene licencia y buscar automáticamente actualizaciones.",
            'Configurar outlook classic con vista de correo a 1 año y activar configurar cuenta manualmente, con archivo de datos .ost en "D:/Correo (No borrar)".',
            "Dejar sobre el perfil del correo la plantilla de firma fija o verificar si el usuario ya la tiene predeterminada.",
            "Iniciar teams con el correo del usuario y desactivar iniciar teams automáticamente, dejar check abrir en segundo plano.",
            "Habilitar uso de onedrive si el usuario tiene licencia y reposar backup en la raíz de la partición d:/.",
            "Descargar todos los archivos en el equipo local siempre que el peso no sature la partición d:/.",
            "Predeterminar acrobat reader para abrir archivos pdf.",
            "Habilitar conexión a escritorio remoto con el usuario de dominio (Desde sysdm.cpl).",
            "Habilitar macros y activex en excel y colocar a turin (file://172.16.1.22) como sitio de confianza (Desde inetcpl.cpl).",
            "Conectar unidades de red correspondientes a las carpetas compartidas del usuario.",
            "Configurar vpn y validar conexión con red wifi libre (Usar celular de soporte, solo portátiles).",
            "Crear acceso directo a backup turin y verificar conexión al ejecutar el .bat.",
            "Copiar accesos directos de aplicaciones colombia y costa rica, dejar .bat en el escritorio para refresh con o:/.",
            "Copiar accesos directos de word, excel, outlook y teams en el escritorio.",
            "Configurar seguridad de java para acceso a oracle web co-cr global privado y público.",
            "Dejar accesos directos en el escritorio de oracle web co-cr en formato .exe verificando acceso.",
            "Cambiar configuración regional para separación de miles con coma y decimales con punto (Desde intl.cpl).",
            "Instalar impresoras del área o dejar la más cercana al puesto de trabajo.",
            "Dejar predeterminada la página https://spradling.group/es-la en edge y chrome.",
            "Instalar módulo de acronis backup, crear carpeta en d:/Datos/[Año en curso] solo para directores y gerentes, validar con infraestructura.",
            "Colocar favoritos o marcadores del usuario en los navegadores (No aplica si es nuevo ingreso).",
            "Verificar que el software instalado cuente con licencia.",
            "Verificar e instalar programas que el usuario utiliza como pdf24, powerbi, scribe, sap logon, bizagi, iris, scada.",
            "Agregar en el caso de mayté las capturas de reporte correcto en intune, entra y defender.",
            "Validar que el perfil del usuario tenga habilitado mfa (Desde entra).",
            "Verificar que el equipo tenga actualizaciones al día windows, office y winget.",
            "Desde bios setup habilitar contraseña admin y system (Solo portátiles).",
            "Realizar inicio de sesión en mayté con el perfil del usuario y validar título, localizaciones, perfil, responsable y grupos.",
            "Habilitar punto de restauración para la unidad c:/ y crear punto con fecha actual (Desde sysdm.cpl).",
            "PARA CONTROL DE INVENTARIO. Asignar activo fijo si el equipo no lo tiene.",
            "Actualizar datos en oracle web co para equipo y monitor según códigos definidos.",
            'Diligenciar checklist y dejarlo en "//172.16.1.22/checklist$/2025/PQN".',
            "Revisar en intune categoría, organización, usuario, etiqueta y grupos. En notas colocar activo y correo.",
            "Sincronizar la cuenta desde configuración y reiniciar el equipo.",
            'Revisar que en entra id aparezca una sola vez como "Microsoft entra hybrid joined".',
            'Verificar en defender que el nombre del equipo termine en "X.proquina.com" y tenga etiquetas correctas.',
            "Realizar offboarding del equipo antiguo antes de eliminarlo de las consolas.",
            "Verificar que las dos particiones del disco estén auto cifradas.",
            'Realizar acta de entrega del equipo desde "//172.16.1.22/checklist$/Actas de entrega".',
            "Solicitar traslado del equipo a la supervisora por teams con número de activo fijo.",
            "Realizar mantenimiento preventivo si el equipo supera los 6 meses de antigüedad.",
            "Realizar limpieza de pantalla y teclado si no es equipo nuevo.",
            "Realizar traslado del equipo viejo, dejarlo vinipelado, marcado y publicar recibimiento en teams.",
        ],
    },
    "terminales": {
        "titulo": "Checklist Proquinal Terminales 2025",
        "empresa": "Proquinal",
        "tipo": "Terminales",
        "plantilla": "plantilla_terminales.xlsx",
        "icono": "🖥️",
        "color": "success",
        "descripcion": "Para terminales de planta",
        "preguntas": [
            'CON USUARIO LOCAL SOPORTE. Crear usuario local "Soporte", asignar contraseña y agregarlo al grupo administradores (Desde compmgmt.msc).',
            'Habilitar usuario administrador y renombrarlo a "Adminpc_pqn", asignar contraseña.',
            "Realizar windows update.",
            "Realizar actualización de drivers (Desde la página oficial del fabricante o usando supportassist).",
            "Instalar y activar características adicionales de framework 3.5 (Desde página microsoft).",
            "Instalar fuentes corporativas ubicadas en (recursospqn$/Instaladores Sistemas/Fuentes corporativas).",
            'Particionar el disco duro. Para disco de 500gb (250 para d y el resto para c). Para disco de 1tb (600 para d y el resto para c). La partición d debe llamarse "Datos". Disco de 250gb no se particiona.',
            'Subir el equipo al dominio de red (proquinal.com). El nombre del equipo debe contener el serial del equipo. Ejemplo "Cby45tf-pqn-col" (Tomar siempre los últimos siete dígitos del serial más la compañía y su regional).',
            'En la descripción del equipo colocar. Ejemplo "Activo xxxxx, correo@spradling.group".',
            'Desde el directorio activo en la ou "Computers" asignar la descripción. Ejemplo "Activo xxxxx, correo@spradling.group". Luego mover el equipo a la ou "Equipos proquinal".',
            "Instalar teamviewer host desde (recursospqn$/Instaladores Sistemas/Teamviewer/2025 - Host) y registrar en la consola admin (Primer nombre y apellido más el hostname del equipo entre paréntesis). Luego comprobar actualizaciones del programa.",
            'Instalar mediante el manual oracle erp proquinal s.a.s ubicado en "Recursospqn$/Recursos 2014/Oracle Install/Manual de instalación oracle.pdf".',
            'Renombrar carpetas de oracle "OraWin95.old" y "Ora9i.old".',
            'Copiar y pegar las carpetas de oracle en c:/ desde la ruta "//recursospqn$/Recursos 2014/Oracle/Oracle Client/Orawin95 y Ora9i/Usuario estandar" las carpetas "Ora9i" y "OraWin95".',
            "Crear la carpeta c:/Listados.",
            'Exportar regedit del usuario o ejecutar según área desde "//recursospqn$/Recursos 2014/Oracle/Oracle Client/Oracle64".',
            "Instalar java jre 8 versión 341 (Desde recursospqn$/Instaladores Sistemas/Java 8 341).",
            "Copiar y pegar las carpetas orapqnen en la raíz de c:/ y backup de turin en (c:/Windows).",
            "Crear variable path para ingreso oracle web con valor c:/Orapqn/lib60.",
            "Crear variable de entorno para oracle (Nombre tns_admin, valor o:/tnsnames).",
            "Probar acceso a aplicaciones colombia con tus credenciales (Antes debe conectar la unidad de red o://172.16.1.22/orapqn$).",
            "Instalar citrix workspace app (Desde la web oficial).",
            "Instalar adobe acrobat reader pdf (Desde la web oficial sin mcafee y en español).",
            "Instalar dell support assist o lenovo services bridge (Desde la web oficial).",
            "Instalar google chrome enterprise (Desde la web oficial).",
            "Agregar en propiedades de red dns. Como principal 172.16.1.1 y como alternativo 172.16.1.32.",
            "Verificar por regedit que exista la variable scada. Nombre de cadena path_scada, valor \\172.16.1.96\\Scada$.",
            "Verificar por regedit que exista la variable para porterías. Nombre de cadena path_visitas, valor c:/Fotos_visitas (Si aplica).",
            "CON USUARIO DE DOMINIO. Cambiar la configuración de energía del equipo. Colocar nunca en opciones de energía, batería solo 3 horas y desactivar inicio rápido.",
            'Direccionar mis documentos a "D:/Datos".',
            "Sincronizar onedrive en la raíz de d:/ y luego configurar onedrive.",
            "Desinstalar programas innecesarios de windows como xbox, solitario, noticias, tiempo, to do.",
            "Habilitar conexión a escritorio remoto con el usuario de dominio.",
            "Colocar a turin (File://172.16.1.22) como sitio de confianza desde opciones de internet.",
            "Predeterminar acrobat reader para abrir archivos pdf.",
            "Crear archivo .bat para reconexión con la unidad o://172.16.1.22/orapqn$.",
            "Copiar accesos directos de aplicaciones colombia y costa rica, crear .bat en el icono de oracle para conexión a o:/.",
            "Instalar office 365 si el usuario tiene licencia, de lo contrario instalar visor.",
            "Instalar microsoft edge y google chrome enterprise.",
            "Dejar en el escritorio accesos directos de oracle web co y cr en formato .exe.",
            "Configurar seguridad de java para acceso a oracle web.",
            "Cambiar configuración regional para separación de miles con coma y decimales con punto.",
            "Crear acceso directo a daruma https://proquinal.darumasoftware.com/app.php/staff/ y dejar como favorito en el navegador.",
            "Crear acceso directo a mayté https://mayte.spradling.group/ y dejar como favorito en el navegador.",
            "Crear acceso directo a la página de sustancias químicas https://spradling.aybapps.net/proquinal.sustancias y dejar como favorito.",
            "Configurar scada \\172.16.1.96 desde el navegador.",
            "Instalar drivers de impresoras (Rótulos y zebras) e importar archivo regedit.",
            "Dejar predeterminada la página https://spradling.group/en-la en todos los navegadores.",
            "Configurar autologon del usuario por regedit. Cambiar autoadminlogon de 0 a 1 y definir defaultuser con dominio.",
            "Crear clave defaultpassword con la contraseña del usuario.",
            "Verificar que el equipo quede con actualizaciones al día windows y office.",
            "Habilitar punto de restauración automática para la unidad c:/ y crear un punto de restauración.",
            "PARA CONTROL DE INVENTARIO. Asignar activo fijo si el equipo no lo tiene.",
            "Actualizar datos en oracle web co para equipo y monitor según códigos definidos.",
            'Diligenciar checklist y dejarlo en "//172.16.1.22/checklist$/2025/PQN".',
            "Revisar en intune categoría, organización, usuario, etiqueta y pertenencia a grupos. En notas colocar activo y correo.",
            "Sincronizar la cuenta desde configuración y reiniciar el equipo.",
            'Revisar que en entra id aparezca una sola vez como "Microsoft entra hybrid joined".',
            'Verificar en defender que el nombre del equipo termine en "X.proquina.com" y tenga las etiquetas correctas.',
            "Realizar offboarding del equipo antiguo antes de eliminarlo de las consolas.",
            "Verificar que las dos particiones del disco estén auto cifradas.",
            'Realizar acta de entrega del equipo desde "//172.16.1.22/checklist$/Actas de entrega".',
            "Solicitar traslado del equipo a la supervisora mediante teams compartiendo número de activo fijo del equipo y monitor.",
            "Realizar mantenimiento preventivo si el equipo supera los 6 meses de antigüedad.",
            "Realizar limpieza de pantalla y teclado si no es equipo nuevo.",
            "Realizar traslado del equipo viejo, dejarlo vinipelado, marcado y publicar recibimiento en teams.",
        ],
    },
    "macos": {
        "titulo": "Checklist Proquinal MacOS 2025",
        "empresa": "Proquinal",
        "tipo": "MacOS",
        "plantilla": "plantilla_macos.xlsx",
        "icono": "🍎",
        "color": "dark",
        "descripcion": "Para MacBook e iMac",
        "preguntas": [
            'CON USUARIO LOCAL ADMINPC_PQN. El usuario de configuración inicial se crea como "Adminpc_pqn" y se asigna contraseña.',
            "Realizar actualizaciones de macos.",
            "Instalar teamviewer host y registrar en la consola de administración.",
            "Crear usuario correspondiente al propietario de la máquina.",
            "CON USUARIO DE DOMINIO. Ingresar con el usuario de la máquina.",
            "Realizar la instalación del portal de microsoft para enrolamiento por intune.",
            "Validar correcto registro en la consola de intune y defender.",
            "Instalar licencia de office correspondiente a la licencia asignada al usuario de la máquina.",
            "Configurar suite de office con la cuenta del usuario.",
            "Configurar onedrive en la máquina y validar si el usuario desea descargar los archivos o dejarlos en la nube.",
            "Instalar microsoft teams y otorgar permisos para compartir pantalla y audio.",
            "Instalar adobe cloud si el usuario tiene licencia.",
            "Validar con el usuario qué aplicativos de la suite de adobe necesita y realizar la instalación correspondiente.",
            "Instalar google chrome y forticlient vpn.",
            "Predeterminar acrobat reader para abrir archivos pdf.",
            "Validar con infraestructura permisos de navegación para el equipo.",
            "Realizar paso de datos del equipo anterior a la nueva máquina.",
            "Revisar que el equipo quede con las últimas versiones de macos monterey, ventura o sonoma, priorizando siempre la más reciente.",
            "Configurar hardware externo que utilice el usuario como tableta de dibujo, graphic pen u otros.",
            "Configurar filevault desde preferencias del sistema, seguridad y privacidad, activar filevault.",
        ],
    },
    "tablets": {
        "titulo": "Checklist Proquinal Tablets 2025",
        "empresa": "Proquinal",
        "tipo": "Tablets",
        "plantilla": "plantilla_tablets.xlsx",
        "icono": "📱",
        "color": "info",
        "descripcion": "Para celulares y tablets",
        "preguntas": [
            "CON USUARIO LOCAL SOPORTE. Antes de iniciar sesión, enrolar en intune escaneando el código QR.",
            "En el archivo Excel se encuentra el QR que debes escanear",
            "Loguear la cuenta de playstore corporativa soportesistemaspqncol@gmail.com.",
            "Iniciar sesión en office 365 con la cuenta corporativa del usuario.",
            "Habilitar inicio de sesión por pin de 4 dígitos y tomar nota para entregar al usuario.",
            "Habilitar bloqueo de la tablet cada 15 minutos como mínimo.",
            "Instalar outlook.",
            "Instalar office word, excel y power point.",
            "Instalar power bi.",
            "Instalar onedrive.",
            "Instalar teamviewer host.",
            "Instalar adobe reader pdf.",
            "Instalar hubspot desde playstore.",
            "Crear acceso directo a daruma https://proquinal.darumasoftware.com/app.php/staff/ y dejar como favorito en el navegador.",
            "Crear acceso directo a mayté https://mayte.spradling.group/ y dejar como favorito en el navegador.",
            "Crear acceso directo a la biblioteca de productos https://library.spradling.group/auth/login y dejar como favorito en el navegador.",
            "Dejar predeterminada la página https://spradling.group/en-la en todos los navegadores.",
            "Verificar si el usuario utiliza otro tipo de software como iris, archivo de planeación o software de diseño.",
            "Verificar que el software instalado en el equipo cuente con licencia.",
            "Dejar la tablet con las últimas actualizaciones disponibles.",
            "PARA CONTROL DE INVENTARIO. Asignar activo fijo.",
            "Diligenciar los datos en oracle del activo correspondiente al equipo con los códigos definidos.",
            "Diligenciar checklist y colocarlo en la carpeta compartida.",
            "Revisar que el dispositivo se visualice en intune, entra y defender, categorizándolo correctamente.",
            "Realizar el traslado del dispositivo viejo y dejarlo marcado con usuario, fecha y responsable en el vinipel.",
        ],
    },
    "calypso": {
        "titulo": "Checklist Calypso CCS CBQ 2025",
        "empresa": "Calypso",
        "tipo": "CCS-CBQ",
        "plantilla": "plantilla_calypso.xlsx",
        "icono": "⚙️",
        "color": "warning",
        "descripcion": "Para equipos Calypso",
        "preguntas": [
            "CON USUARIO LOCAL SOPORTE. Al formatear el equipo, en la página de bienvenida iniciar solo hasta el momento en que solicita conectar a internet.",
            "Conectar a una red de internet y no continuar.",
            "En la página de bienvenida abrir la cmd con (Fn + F10) y ejecutar los tres comandos del manual autopilot.",
            "Al solicitar las credenciales, ingresar las propias para que el equipo se inscriba en el grupo empresarial.",
            'Agregar el equipo al grupo en intune "Grp_dispositivos windows autopilot ccs-col" para la instalación de aplicaciones.',
            "Desde el grupo windows autopilot asignar perfil y ajustar etiquetas. Correo del destinatario, nombre del dispositivo y etiqueta de empresa. Luego sincronizar y reiniciar el equipo.",
            "Iniciar sesión con el usuario asignado en el equipo usando el correo del destinatario para la autopreparación.",
            'Habilitar y renombrar el usuario administrador a "Adminpc_ccs" y asignar contraseña (Desde compmgmt.msc). Crear usuario local "Soporte", agregarlo al grupo administradores y asignar contraseña.',
            "Verificar activación de la licencia de windows.",
            "Instalar .net framework 3.5 y habilitar las características (Desde optionalfeatures).",
            "Realizar windows update.",
            "Verificar controladores del equipo y realizar actualización de drivers.",
            "Particionar el disco duro si es posible. Disco de 500gb (250 para d y el resto para c). Disco de 1tb (600 para d y el resto para c).",
            "Instalar comerssia si lo requiere, teniendo presente cambiar el formato de la hora y demás configuraciones.",
            'En la descripción del equipo colocar "Activo xxxxxx, correo@spradling.group".',
            'Cambiar el nombre del equipo, debe contener el service tag. Ejemplo "Cby45tf-ccs-col" (Tomar los últimos siete caracteres del serial más regional y país).',
            "En grupo de trabajo colocar la ciudad o sede a la que pertenece el equipo.",
            "CON USUARIO DE AZUREAD. Cambiar la configuración de energía del equipo. Colocar nunca en opciones de energía y batería solo 3 horas.",
            "Direccionar mis documentos a la carpeta d:/Datos.",
            "Validar instalación automática de office 365 y buscar actualizaciones.",
            "Validar instalación automática de adobe acrobat reader pdf.",
            "Validar instalación automática de google chrome enterprise.",
            "Validar instalación automática de teamviewer host.",
            "Configurar outlook classic con archivo .ost en d:/Correo (No borrar).",
            "Iniciar teams habilitando inicio en segundo plano y desactivando inicio con windows.",
            "Quitar programas innecesarios por defecto como noticias, xbox, tiempo, to do, solitario.",
            "Habilitar uso de onedrive del usuario si tiene licencia y guardar la ubicación en d:/.",
            'Deshabilitar la opción "Ahorre espacio y descargue los archivos cuando los use" y no sincronizar documentos, escritorio ni imágenes.',
            "Predeterminar acrobat reader para abrir archivos pdf.",
            "Validar que el equipo tome el fondo según la política de intune.",
            "Instalar teamviewer host y registrarlo en la consola de administración con la nomenclatura adecuada.",
            "Instalar fuentes corporativas.",
            "Copiar accesos directos de office word, excel, onenote y outlook classic.",
            "Cambiar configuración regional para separación de miles y decimales, punto para decimales y coma para miles.",
            "Dejar acceso directo a sap e iniciar sesión con el usuario sapcalypso\\cal-* y su contraseña.",
            "Instalar software vpn forticlient sin configurar.",
            "Instalar citrix workspace app sin configurar.",
            "Dejar predeterminada la página https://www.tiendascalypso.com en ambos navegadores.",
            "Crear acceso directo a mayté https://mayte.spradling.group/ y dejarlo como favorito en ambos navegadores.",
            "Realizar primer inicio de sesión en mayté con el correo del destinatario y dejarlo categorizado correctamente.",
            "Habilitar mfa del usuario.",
            "Habilitar contraseña de bios admin y system solo si es portátil.",
            "Verificar si el usuario utiliza otro tipo de software como powerbi, autocad, smartview o software de diseño.",
            "Verificar que el equipo quede con actualizaciones al día windows y office.",
            "PARA CONTROL DE INVENTARIO. Revisar que el equipo tenga activo fijo calypso, de lo contrario validar con el encargado.",
            "Habilitar punto de restauración automática para la unidad c:/.",
            "Diligenciar checklist y colocarlo en la carpeta compartida.",
            "Crear imagen de la partición c:/ sistemapqn y crear readme informativo en d:/Imagen (No borrar) solo para equipos especiales.",
            "Revisar que el equipo se visualice en intune, entra y defender y quede categorizado correctamente.",
            "Validar que no esté duplicado en las tres consolas de administración, luego sincronizar y reiniciar el equipo.",
            "Tomar capturas del reporte en intune, entra y defender y agregarlas al caso de configuración de equipo en mayté.",
        ],
    },
}


def get_checklist(tipo: str) -> dict:
    """Obtener checklist por tipo"""
    return CHECKLISTS.get(tipo)


def get_all_checklists() -> dict:
    """Obtener todos los checklists"""
    return CHECKLISTS


def checklist_exists(tipo: str) -> bool:
    """Verificar si existe un checklist"""
    return tipo in CHECKLISTS
